version: '3.8'
services:
  nas-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # volumes:
    #   # Map your NAS storage directory
    #   - /path/to/nas/storage:/backend/storage
    #   # Map your config files if needed
    #   - /path/to/config:/backend/config
    environment:
      - NODE_ENV=production
      # Add other environment variables
    restart: unless-stopped
    # Optional: set user permissions
    user: "1000:1000"
